// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCdzqTQEQQO9JVEfet822pc7xJiDADtR30',
//     appId: '1:967478861756:web:934ae9e3ad7a14847795b9',
//     messagingSenderId: '967478861756',
//     projectId: 'todoapp-2023-619c2',
//     authDomain: 'todoapp-2023-619c2.firebaseapp.com',
//     storageBucket: 'todoapp-2023-619c2.appspot.com',
//     measurementId: 'G-T7DX3SK6DH',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAaEHTwnbVaXzOVXyLuzVihrXEcQ-yXIMc',
//     appId: '1:967478861756:android:8c1d0e431d3c20e77795b9',
//     messagingSenderId: '967478861756',
//     projectId: 'todoapp-2023-619c2',
//     storageBucket: 'todoapp-2023-619c2.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAwzDLN0z0pAXJn2QdrOAK7aHwzdAfoLys',
//     appId: '1:967478861756:ios:8cff6a1fa0dfda527795b9',
//     messagingSenderId: '967478861756',
//     projectId: 'todoapp-2023-619c2',
//     storageBucket: 'todoapp-2023-619c2.appspot.com',
//     iosClientId: '967478861756-ofafege05llljgjplgabsomc23qumptm.apps.googleusercontent.com',
//     iosBundleId: 'com.example.todoApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAwzDLN0z0pAXJn2QdrOAK7aHwzdAfoLys',
//     appId: '1:967478861756:ios:edec5e059221c3b37795b9',
//     messagingSenderId: '967478861756',
//     projectId: 'todoapp-2023-619c2',
//     storageBucket: 'todoapp-2023-619c2.appspot.com',
//     iosClientId: '967478861756-7cao9m94os01app7rvkbse05s32htqnu.apps.googleusercontent.com',
//     iosBundleId: 'com.example.todoApp.RunnerTests',
//   );
// }
