name: todo_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.2
  country_flags: ^2.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  fancy_shimmer_image: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.3
  flutter_iconly: ^1.0.2
  flutter_localization: ^0.1.14
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  hive: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  lottie: ^2.7.0
  page_transition: ^2.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/products/
    - assets/user_images/
    - assets/user_images/bag/
    - assets/user_images/banners/
    - assets/user_images/categories/
    - assets/user_images/profile/
    - assets/admin_images/
    - assets/admin_images/categories/
    - assets/admin_images/dashboard/

  fonts:
    - family: Laila
      fonts:
        - asset: assets/fonts/Laila-Medium.ttf
        - asset: assets/fonts/Laila-Regular.ttf
          weight: 700

    - family: Work_Sans
      fonts:
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900
